### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-atom3#21]
I clicked "Build PROS Project" from inside a project with no file currently open.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pros-atom3](https://github.com/purduesigbots/pros-atom3) package 1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\firey\.pros-editor\packages\pros-atom3\lib\commands.js:51

TypeError: Cannot read property 'getPath' of undefined
    at HTMLElement.didDispatch (/packages/pros-atom3/lib/commands.js:51:63)
    at CommandRegistry.handleCommandEvent (C:/Program Files/PROS/editor/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (C:/Program Files/PROS/editor/resources/app/src/command-registry.js:273:23)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:130:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:109:12)
```

### Commands

```
     -1:25.3.0 core:move-down (input.hidden-input)
     -1:25 core:delete (input.hidden-input)
     -1:24.3.0 core:backspace (input.hidden-input)
     -1:23.9.0 core:move-up (input.hidden-input)
     -1:23.6.0 editor:newline (input.hidden-input)
     -1:23.4.0 core:move-up (input.hidden-input)
     -1:19.3.0 core:save (input.hidden-input)
  4x -1:10.4.0 core:backspace (input.hidden-input)
     -1:07.1.0 editor:newline (input.hidden-input)
     -1:01.2.0 core:move-down (input.hidden-input)
     -1:00.8.0 core:move-up (input.hidden-input)
  2x -0:59.9.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:56 snippets:next-tab-stop (input.hidden-input)
     -0:54.4.0 core:save (input.hidden-input)
  5x -0:45.2.0 core:close (input.hidden-input)
     -0:33.4.0 pros:build (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.24 
ide-cquery 0.13.6 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
pros-atom3 1.0.1 
terminal-tab-plus 0.5.9 
tool-bar 1.1.10 
tool-bar-main 0.0.11 
```

**Comment by Octogonapus** [comment]
The "with no file open" bit is important. It worked when I had a file open.

**Comment by HotelCalifornia** [comment]
There's not really a good way to detect the currently selected project unless there is a file open. I'd be open to suggestions as to how to improve that process, though.

**Comment by Octogonapus** [comment]
Maybe you can use the last open file? If there is no previously open file, then you could show a better message.
