### ISSUE TITLE
Failed to activate the pros-atom3 package

### ISSUE THREAD

**Issue by iuyte** [purduesigbots/pros-atom3#23]
[Enter steps to reproduce:]

 1. Open Atom
 2. ??? It loads I guess

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: "Fedora release
**Thrown From**: [pros-atom3](https://github.com/purduesigbots/pros-atom3) package 1.0.1

### Stack Trace

Failed to activate the pros-atom3 package

```
At Cannot find module 'etch'

Error: Cannot find module 'etch'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/pros-atom3/lib/pros-atom3.js:7:13)
    at /packages/pros-atom3/lib/pros-atom3.js:78:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:220:40)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/share/atom/resources/app/src/package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/usr/share/atom/resources/app/src/package-manager.js:650:18)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
file-icons 2.1.15 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
platformio-ide-terminal 2.8.4 
pros-atom3 1.0.1 
tool-bar 1.1.10 
tool-bar-main 0.0.11 
```

**Comment by jasmangle** [comment]
Same issue here using macOS Version 10.13.6 with Atom 1.30.0.

Edit: Ok, just updated all dependencies and now it says `Cannot find module 'which'`

**Comment by HotelCalifornia** [comment]
I'm really not sure why it wouldn't be able to find `etch`, which is a core package in Atom...

@iuyte were you able to resolve the issue by updating all dependencies also?

**Comment by iuyte** [comment]
I no longer have any issue with it
