### ISSUE TITLE
Error Uploading - Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by therealamills** [purduesigbots/pros-atom3#36]
[Enter steps to reproduce:]

1. Successfully compile project via PROS -> Build -> All
2. PROS -> Upload Project
 

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [pros-atom3](https://github.com/purduesigbots/pros-atom3) package 1.1.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/PROS%20Editor.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /packages/pros-atom3/node_modules/@purduesigbots/pros-cli-middleware/dist/util.js:110:38)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -1:12.4.0 pros:upload-prompt (input.hidden-input)
     -0:43.6.0 pros:build-all (input.hidden-input)
     -0:22.3.0 core:save (input.hidden-input)
     -0:19.2.0 pros:build-all (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy 0.7.0 
busy-signal 2.0.0 
file-icons 2.1.30 
git-clone 0.2.0 
git-plus 8.6.1 
ide-cquery 0.14.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
pros-atom3 1.1.0 
terminal-tab-plus 0.5.11 
tool-bar 1.1.11 
tool-bar-main 0.0.11 
```

**Comment by edjubuh** [comment]
I suspect this is the same issue going on in #37, so let's just track the conversation there.
